### PR TITLE
Process segmented text in LoadFile

### PR DESCRIPTION
**Pull request by monsieurzhang**

### CODE REVIEW

**Comment by natsegal** [comment]
Looks ok to me

**Comment by guillaumekln** [comment]
Do we actually need this change? It does seem like the `continuation` flag is no longer useful because `len(meta)` already returns the number of parts.

**Comment by natsegal** [comment]
At the very least we need the detokenization in TU that takes parts into account.
And by the way, this raises another question/ambiguity related to parts : should we always have only one part in detokenized version or should it have the same number of parts as tok and stick them together at consumer level  ?
For example, entities and classifiers in their current implementation need both tokenized and detokenized input, on part level.

As for checking the contents of the meta, it does seem a little excessive now, when the information is always the same in meta, but doesn't it leave the possibility to extend this information in future ?

**Comment by guillaumekln** [comment]
> At the very least we need the detokenization in TU that takes parts into account.

I'm thinking we could join the multiparts directly in the Loader, before building the TU?

> And by the way, this raises another question/ambiguity related to parts : should we always have only one part in detokenized version or should it have the same number of parts as tok and stick them together at consumer level ?
For example, entities and classifiers in their current implementation need both tokenized and detokenized input, on part level.

Ideally, operators should not have to think about that. Another reason we should enforce single-part in the pipeline.

>As for checking the contents of the meta, it does seem a little excessive now, when the information is always the same in meta, but doesn't it leave the possibility to extend this information in future ?

The concern is that `continuation` convey the same information as `len(meta)`, but with extra work. It is redundant and so error-prone. I would propose to ignore the content of metadata when it comes to counting the number of parts.

**Comment by natsegal** [comment]
> I'm thinking we could join the multiparts directly in the Loader, before building the TU?

OK, in this case we completely get rid of the multi-part processing inside the pipeline in postprocess ?

And in preprocess, we hide multi-part interface for all operators except sentence splitting ?

Am I following you ? :D

**Comment by guillaumekln** [comment]
Yes, that's the idea.

@monsieurzhang I propose that I take this PR based on the conversation above.

**Pull request closed without merging**
