### PR TITLE
Build info for standalone model

### PR DESCRIPTION
**Pull request by natsegal**

### CODE REVIEW

**Comment by guillaumekln** [comment]
Maybe we could just add a new argument to `_summarize_data_distribution` like `hide_filenames`?

**Comment by natsegal** [comment]
I wanted to avoid a parameter since it won't be used at all in the base framework. But if you think it's better, I'll change.

**Comment by guillaumekln** [comment]
Ok, it makes sense. In that case, I suggest not mentioning the corpus anonymization in the comment since it is not done in the base framework.

**Review by guillaumekln — APPROVED** [review]

**Comment by natsegal** [comment]
Yes, I removed the comment.

**Pull request merged**
